# Generated by Django 5.0.6 on 2024-11-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=300)),
                ('receiver', models.CharField(max_length=300)),
                ('origin', models.CharField(max_length=400)),
                ('order_date', models.CharField(max_length=100)),
                ('order_status', models.BooleanField(default=False)),
                ('shipment_location', models.CharField(max_length=400)),
                ('shipment_date', models.CharField(max_length=100)),
                ('shipment_status', models.BooleanField(default=False)),
                ('delivery_destination', models.CharField(max_length=400)),
                ('delivery_date', models.CharField(max_length=100)),
                ('delivery_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PotCovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epot_cover', models.CharField(max_length=300)),
                ('ppot_cover', models.CharField(max_length=300)),
            ],
        ),
    ]
