# Generated by Django 5.0.6 on 2024-11-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mayne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='potcovers',
            name='ipot_cover',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
